#!/usr/bin/env php
<?php
/*
|--------------------------------------------------------------------------
| Requiring auto loader
|--------------------------------------------------------------------------
|
| Including auto loader
*/
require __DIR__ . '/bootstrap/autoloader.php';

/*
|--------------------------------------------------------------------------
| Requiring kernel
|--------------------------------------------------------------------------
|
| Includes kernel class initialisation
*/
/** @var \Venta\Contract\Kernel $kernel */
$kernel = require __DIR__ . '/bootstrap/kernel.php';

/*
|--------------------------------------------------------------------------
| Creating cli Application
|--------------------------------------------------------------------------
|
| Initializes application and boots kernel
*/
$app = new \Venta\Application\ConsoleApplication($kernel);

/*
|--------------------------------------------------------------------------
| Running Application
|--------------------------------------------------------------------------
|
| Application processes Input and passes results to Output
*/
$app->run();