#!/usr/bin/env php
<?php
/*
|--------------------------------------------------------------------------
| Requiring auto loader
|--------------------------------------------------------------------------
|
| Including auto loader
*/
require __DIR__ . '/bootstrap/autoloader.php';

/*
|--------------------------------------------------------------------------
| Requiring main application class
|--------------------------------------------------------------------------
|
| Including application class initialisation
*/
/** @var \Venta\Contract\Application $app */
$app = require __DIR__ . '/bootstrap/application.php';

/*
|--------------------------------------------------------------------------
| Resolving kernel out of container
|--------------------------------------------------------------------------
|
| Kernel will handle application execution process
*/
/** @var \Venta\Contract\Kernel\ConsoleKernel $kernel */
$kernel = $app->make(
    \Venta\Contract\Kernel\ConsoleKernel::class,
    ['name'=>'Venta Console Application', 'version'=>$app->version()]
);

/*
|--------------------------------------------------------------------------
| Passing Apllication
|--------------------------------------------------------------------------
|
| Passing application instance to console kernel
*/
$kernel->setApplication($app);

/*
|--------------------------------------------------------------------------
| Handling request
|--------------------------------------------------------------------------
|
| This function call will make application run and handle request object
| producing response object
*/
$status = $kernel->handle(
    $app->make(\Symfony\Component\Console\Input\InputInterface::class),
    $app->make(\Symfony\Component\Console\Output\OutputInterface::class)
);

/*
|--------------------------------------------------------------------------
| Terminate our application
|--------------------------------------------------------------------------
|
| Termination is called on application here
*/
$kernel->terminate();

/*
|--------------------------------------------------------------------------
| Output of response
|--------------------------------------------------------------------------
|
| Since it is console application, we are exiting with result status
*/
exit($status);