#!/usr/bin/env php
<?php
/*
|--------------------------------------------------------------------------
| Requiring auto loader
|--------------------------------------------------------------------------
|
| Including auto loader
*/
require __DIR__ . '/bootstrap/autoloader.php';

/*
|--------------------------------------------------------------------------
| Requiring main application class
|--------------------------------------------------------------------------
|
| Including application class initialisation
*/
$app = require __DIR__ . '/bootstrap/application.php';

/*
|--------------------------------------------------------------------------
| Resolving kernel out of container
|--------------------------------------------------------------------------
|
| Kernel will handle application execution process
*/
/** @var \Venta\Framework\Contracts\Kernel\ConsoleKernelContract $kernel */
$kernel = $app->make(\Venta\Framework\Contracts\Kernel\ConsoleKernelContract::class);

/*
|--------------------------------------------------------------------------
| Handling request
|--------------------------------------------------------------------------
|
| This function call will make application run and handle request object
| producing response object
*/
$status = $kernel->handle();

/*
|--------------------------------------------------------------------------
| Output of response
|--------------------------------------------------------------------------
|
| Since it is console application, we are exiting with result status
*/
exit($status);